Add support for STM32duino DFU bootloader.
qmk/qmk_toolbox pull request #166
Opened 2020-01-29 17:03 UTC by tzarc

## Description

Adds support for the STM32duino bootloader, VID=0x1eaf, PID=0x0003.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Documentation

2020-01-29 18:58 UTC, tzarc commented
I'm not... but I can probably have a stab.

2020-01-29 19:58 UTC, nooges commented
@tzarc ping/tag me if needed regarding obj-c

2020-01-29 23:10 UTC, fauxpark commented on windows/QMK Toolbox/MainWindow.cs
> +            _printer.PrintResponse(" - ARM DFU (STM32, Kiibohd, STM32duino) via dfu-util (http://dfu-util.sourceforge.net/)\n", MessageType.Info);
Should also be added to Program.cs, and the readme. For macOS, main.m and AppDelegate.m.

2020-01-29 23:10 UTC, fauxpark commented on windows/QMK Toolbox/USB.cs
> +            else if (MatchVid(deviceId, 0x1eaf) && MatchPid(deviceId, 0x0003)) // Detects STM32duino Bootloader
```suggestion
            else if (MatchVid(deviceId, 0x1EAF) && MatchPid(deviceId, 0x0003)) // Detects STM32duino Bootloader
```

2020-02-05 05:41 UTC, fauxpark commented
Do we also need to add this bootloader's VID/PID to drivers.txt?

2020-02-05 06:23 UTC, tzarc commented
> 
> 
> Do we also need to add this bootloader's VID/PID to drivers.txt?

If that's to support Zadig, I don't believe it's needed..., I certainly didn't need to install anything other than the default that came up.

I'm actually thinking that perhaps this isn't a PR that should be merged -- in order to get uploads to work with the STM32duino bootloader I've been finding that "auto flash" needs to be turned on in toolbox. By the time it shows up as a new DFU bootloader device in toolbox it's already too late, as it's already started executing any user code that was already on the board.

Given the small number of people targeting this bootloader (are there any?) I'm inclined to just close without merge. Thoughts?

2020-02-05 07:12 UTC, fauxpark commented
Looks like libusb-win32:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/drivers/win/src/libwdi-1.2.4-with-usbser-driver-v3.diff#L9
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/drivers/win/install_drivers.bat#L4

As for the auto flash being necessary, it doesn't sound any worse than Caterina. I'm not averse to merging if that's the case. We can probably also optimise the whole bootloader detection process, to speed it up, though that's easier said than done 😄

2020-10-30 19:57 UTC, awkannan commented
> > Do we also need to add this bootloader's VID/PID to drivers.txt?
> 
> If that's to support Zadig, I don't believe it's needed..., I certainly didn't need to install anything other than the default that came up.
> 
> I'm actually thinking that perhaps this isn't a PR that should be merged -- in order to get uploads to work with the STM32duino bootloader I've been finding that "auto flash" needs to be turned on in toolbox. By the time it shows up as a new DFU bootloader device in toolbox it's already too late, as it's already started executing any user code that was already on the board.
> 
> Given the small number of people targeting this bootloader (are there any?) I'm inclined to just close without merge. Thoughts?

Just gonna add my 2c - the stm32duino bootloader does support a boot pin that can be held high to put it into bootloader mode. For this reason, I think it's not a bad idea to merge this.

Also, autoflash is a viable option!

2020-12-16 06:44 UTC, fauxpark commented
> Just gonna add my 2c - the stm32duino bootloader does support a boot pin that can be held high to put it into bootloader mode. For this reason, I think it's not a bad idea to merge this.

Aha! I was trying to figure out why I wasn't experiencing the immediate jump to user code tzarc mentioned above. Turns out I completely missed the `binaries` directory in the repo and flashed the one in `bootloader_only_binaries`. Sure enough it's now a serial device and won't stay in bootloader when I hit the reset button, but if I flip the BOOT1 jumper, it does.

I'm just waiting on a rebase of this PR and for the reviews to be applied, as well as adding the device to drivers.txt, then I think it can be merged.

2020-12-17 05:05 UTC, fauxpark requested changes

2020-12-17 05:05 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +                RunProcess("dfu-util.exe", $"-a 2 -d 1eaf:0003 -R -D \"{file}\"");
```suggestion
                RunProcess("dfu-util.exe", $"-a 2 -d 1EAF:0003 -R -D \"{file}\"");

```

2020-12-17 05:25 UTC, fauxpark approved these changes

2020-12-17 05:25 UTC, merged