Add support for STM32Duino bootloaders on macOS
qmk/qmk_toolbox pull request #229
Opened 2020-09-23 02:23 UTC by jhawthorn

Similar to #166, but for macOS 🍏.

## Description

Adds support for the STM32duino bootloader, VID=0x1eaf, PID=0x0003. A number of keyboards in qmk_firmware already target this style of bootloader. It's very convenient on STM32f1 devices, which don't ship with their own or DIY keyboards based on the popular bluepill breakout.

Bootloader is https://github.com/rogerclarkmelbourne/STM32duino-bootloader which also has a few forks.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

2020-09-23 02:24 UTC, jhawthorn commented
If it helps to get this merged I'm happy to rebase this onto #166 and address the feedback there 🙂

2020-09-23 07:08 UTC, fauxpark commented
@tzarc ?

2020-10-23 20:19 UTC, tzarc commented
Totally didn't see this until now. If you want to get this in, if it's own accord, feel free. I guess we can revisit the Windows side of things too.

2020-12-05 15:11 UTC, fauxpark commented
I am now in possession of a Bluepill, and my ST-Link should be arriving sometime this week, so I'll be able to test out both of these PRs soon.

2020-12-17 05:41 UTC, tzarc commented
#166 is now in.

2020-12-17 06:02 UTC, fauxpark requested changes

2020-12-17 06:02 UTC, fauxpark commented on osx/qmk_toolbox/Flashing.m
> +        [self runProcess:@"dfu-util" withArgs:@[@"-a", @"2", @"-d", @"1eaf:0003", @"-R", @"-D", file]];
```suggestion
        [self runProcess:@"dfu-util" withArgs:@[@"-a", @"2", @"-d", @"1EAF:0003", @"-R", @"-D", file]];
```

2020-12-24 06:25 UTC, drashna approved these changes

2020-12-24 06:27 UTC, fauxpark approved these changes

2020-12-24 06:27 UTC, fauxpark commented
Thanks!

2020-12-24 06:28 UTC, merged