Add support for flashing APM32 via DFU
qmk/qmk_toolbox pull request #238
Opened 2020-11-09 05:39 UTC by awkannan

## Description

Add support for flashing APM32 via DFU.
These are pin compatible with STM32.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

2020-11-09 08:24 UTC, fauxpark requested changes

2020-11-09 08:24 UTC, fauxpark commented on osx/qmk_toolbox/Flashing.m
> +        [self runProcess:@"dfu-util" withArgs:@[@"-a", @"0", @"-d", @"314b:0106", @"-s", @"0x8000000:leave", @"-D", file]];
```suggestion
        [self runProcess:@"dfu-util" withArgs:@[@"-a", @"0", @"-d", @"314B:0106", @"-s", @"0x8000000:leave", @"-D", file]];
```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +        Apm32,
```suggestion
        Apm32Dfu,

```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +                FlashApm32(mcu, file);
```suggestion
            if (Usb.CanFlash(Chipset.Apm32Dfu))
                FlashApm32Dfu(mcu, file);

```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +        private void FlashApm32(string mcu, string file)
```suggestion
        private void FlashApm32Dfu(string mcu, string file)

```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +                RunProcess("dfu-util.exe", $"-a 0 -d 314b:0106 -s 0x08000000:leave -D \"{file}\"");
```suggestion
                RunProcess("dfu-util.exe", $"-a 0 -d 314B:0106 -s 0x08000000:leave -D \"{file}\"");

```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/USB.cs
> +            else if (MatchVidPid(deviceId, 0x314b, 0x0106)) // APM32 DFU
```suggestion
            else if (MatchVidPid(deviceId, 0x314B, 0x0106)) // APM32 DFU
```

2020-11-09 08:24 UTC, fauxpark commented on windows/QMK Toolbox/USB.cs
> +                _devicesAvailable[(int)Chipset.Apm32] += connected ? 1 : -1;
```suggestion
                _devicesAvailable[(int)Chipset.Apm32Dfu] += connected ? 1 : -1;
```

2020-11-09 21:44 UTC, fauxpark commented
So I just discovered something odd... the dfu-util command for the STM32 bootloader specifies the wrong VID (`0482`) in the macOS code, and yet it is able to flash my Proton-C just fine. So it seems like the `-d` flag is being ignored. Maybe we don't need a separate flasher for APM32? Or is dfu-util simply reading the suffix instead?

If so... I have a plan to add `BOOTLOADER = stm32-dfu` into QMK, which currently would only set the dfu-util and dfu-suffix arguments, but this coupled with an `apm32-dfu` option would probably allow us to remove the `-d` flag altogether and just have the STM32 flasher handle both in a much more generic fashion.

2020-11-10 01:34 UTC, awkannan commented
@fauxpark I've only tested on Windows, but the -d does apply.

WIthout the -d, dfu-util will flash any dfu device that's connected, and skips the suffix check.

I can't speak to why the mac os x one is working. Are you sure that there is a suffix on the bin file?

2020-11-10 02:29 UTC, fauxpark commented
Just from a quick look at the code, it doesn't seem like a lack of `-d` skips the suffix check. In fact, it appears dfu-util specifically inspects the suffix to determine which device to flash:

```c
		dfu_load_file(&file, MAYBE_SUFFIX, MAYBE_PREFIX);
		/* If the user didn't specify product and/or vendor IDs to match,
		 * use any IDs from the file suffix for device matching */
		if (match_vendor < 0 && file.idVendor != 0xffff) {
			match_vendor = file.idVendor;
			printf("Match vendor ID from file: %04x\n", match_vendor);
		}
		if (match_product < 0 && file.idProduct != 0xffff) {
			match_product = file.idProduct;
			printf("Match product ID from file: %04x\n", match_product);
		}

```
https://sourceforge.net/p/dfu-util/dfu-util/ci/master/tree/src/main.c#l368

If there is no suffix (recognised here as `idVendor`/`idProduct` set to `0xFFFF`), then `-d` would be needed (and dfu-util spits out a warning afterwards that it is missing).

Thus if we are able to add the correct suffix during compilation, through `BOOTLOADER`, there should be no need for the duplicate flashing method, at the very least. The detection stuff could all stay, so that the Toolbox correctly reports APM32 rather than STM32, but they would both call the same method.

2020-11-10 19:06 UTC, awkannan commented
I think the main issue here, though, is each bin file can only have a single suffix. In this instance, the same firmware can work with both STM32 and APM32.

Testing locally, with a bin file with no suffix, and a dfu-util command with no `-d` specified, it'll flash both STM32 and APM32 just fine, thought it may throw a warning.

But if someone has both an STM32 and APM32 device plugged in and in DFU mode, it'll just pick one at random iirc.
Which is why I think no suffix + -d in toolbox is probably the best way.

Then again, this is the same problem if someone has 2 STM32 devices plugged in in DFU mode... I can see it both ways.

2020-11-10 22:00 UTC, fauxpark commented
I see this primarily as a problem with how the Toolbox is currently designed - if you have multiple bootloader devices (of any kind) connected, it will attempt to flash all of them. Eventually there will be some refactoring and UI updates to allow users to select which device to flash. But for the time being, I guess it is kind of an unspoken rule that you should only flash one board at a time.

IMO the correct suffix should be set at compile time, so that dfu-util does not print the warning message - this might confuse users, thinking that something went wrong. I've seen this happen before with other things, not just the Toolbox but also QMK compilation itself.

2020-11-11 18:41 UTC, awkannan commented
> IMO the correct suffix should be set at compile time, so that dfu-util does not print the warning message - this might confuse users, thinking that something went wrong. I've seen this happen before with other things, not just the Toolbox but also QMK compilation itself.

The issue that for a given firmware, they can be multiple correct suffixes. STM32F072CBT6 firmware works on APM32F072CBT6, and vice versa but they have different suffixes.

We can implement logic in QMK Toolbox to strip/re-add the suffix if it's `0483:DF11` and we are flashing APM32. This was the first approach I suggested but @drashna suggested just clearing out the suffix.

2020-11-12 03:00 UTC, fauxpark commented
Personally I would prefer to stay ahead of the warning message, because at some point dfu-util is going to update, and this will not work anymore. If that means splitting boards up into STM32 and APM32 "revisions", so be it. (you would only need to set the `DFU_ARGS`/`DFU_SUFFIX_ARGS`, or potentially `BOOTLOADER`, though)

See also the mdloader drama, where Drop substituted their CTRL/ALTs' MCUs for the same one but with more flash, resulting in nothing being detected by mdloader because the chip ID was different.

2020-11-12 05:55 UTC, sigprof commented
Apparently there is an option to append the DFU suffix with wildcard values (0xffff) for `idVendor` and `idProduct`, so that dfu-util won't complain about the missing suffix, but also won't perform the extra VID:PID check.

2020-11-27 20:26 UTC, awkannan commented
Given that 0xFFFF 0xFFFF works as a "wildcard" suffix, I think this is still the way to go.

2020-11-28 01:28 UTC, fauxpark requested changes
Could you also add APM32 to the supported bootloaders list (ie `ARM DFU (STM32, APM32, Kiibohd)`) in readme.md, AppDelegate.m, main.m, MainWindow.cs and Program.cs?

Also, what's the "Bus reported device description" for this bootloader in Device Manager? I'd like to know so I can list it in the Zadig docs:
![image](https://user-images.githubusercontent.com/4781841/100491104-3aa8ae80-3175-11eb-9c56-a9a0270a0918.png)

2020-11-28 01:28 UTC, fauxpark commented on windows/QMK Toolbox/Flashing.cs
> +
```suggestion

```

2020-12-02 22:18 UTC, awkannan commented
@fauxpark I'll rebase and make those suggested changes tonight. Thanks!

2021-01-03 03:47 UTC, fauxpark approved these changes

2021-01-03 03:56 UTC, tzarc commented
@fauxpark do we need to add the VID/PID pair to `drivers.txt`?

2021-01-03 03:58 UTC, fauxpark commented
Oops, yeah.

2021-01-03 04:04 UTC, awkannan commented
Added to drivers.txt

2021-01-03 04:04 UTC, tzarc approved these changes

2021-01-03 04:04 UTC, merged