Migrate release process away from archived action
qmk/qmk_toolbox pull request #261
Opened 2021-04-30 22:19 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

2021-05-01 11:31 UTC, fauxpark requested changes

2021-05-01 11:31 UTC, fauxpark commented on .github/workflows/build.yml
> +    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
```suggestion
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
```

2021-05-02 02:06 UTC, fauxpark approved these changes

2021-05-18 16:11 UTC, nooges approved these changes

2021-07-14 17:46 UTC, fauxpark commented
Needs a rebase, I did part of this in #279

2021-07-16 06:09 UTC, fauxpark commented
Didn't realise I could resolve the conflict myself...

2021-07-16 06:10 UTC, merged