Added support of WB32 DFU for MacOs.
qmk/qmk_toolbox pull request #320
Opened 2021-12-07 09:51 UTC by wb-Joy

Added support of WB32 DFU for MacOs.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

2021-12-07 19:44 UTC, fauxpark commented
Package should be submitted to Homebrew and binary taken from there.
https://github.com/homebrew/homebrew-core

See #292

2022-04-17 09:14 UTC, fauxpark requested changes

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox/USB/Bootloader/BootloaderType.h
>      BootloaderTypeUSBTinyISP,
```suggestion
    BootloaderTypeUSBAsp,
    BootloaderTypeUSBTinyISP,
    BootloaderTypeWB32DFU,
```

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox/USB/USBListener.m
>  #import "USBTinyISPDevice.h"
```suggestion
#import "USBAspDevice.h"
#import "USBTinyISPDevice.h"
#import "WB32DFUDevice.h"
```

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox/USB/USBListener.m
> +        case BootloaderTypeWB32DFU:
Move below `BootloaderTypeUSBTinyISP`

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox/USB/USBListener.m
> +        case 0x342D: // WestBerryTech
Move below `0x314B`

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox/USB/Bootloader/WB32DFUDevice.m
> +        [self printMessage:@"This file format is not the type supported by wB32-dFU-updater_cli!" withType:MessageType_Error];
```suggestion
        [self printMessage:@"Only firmware files in .bin or .hex format can be flashed with wb32-dfu-updater_cli!" withType:MessageType_Error];
```

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
> +				9BE10718275F4CFE00C708D5 /* wb32-dfu-updater_cli in Resources */,
Move below `teensy_loader_cli`

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
> +				9B7999ED280AA1C8007469DA /* WB32DFUDevice.h */,
Move below `USBTinyISPDevice`

2022-04-17 09:14 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
> +				9BE10717275F4CFE00C708D5 /* wb32-dfu-updater_cli */,
Move below `teensy_loader_cli`

2022-04-17 09:35 UTC, wb-Joy commented
The format has been adjusted.

2022-04-18 13:33 UTC, fauxpark commented
Waiting for https://github.com/Homebrew/homebrew-core/pull/98739

2022-04-21 12:13 UTC, fauxpark requested changes

2022-04-21 12:13 UTC, fauxpark commented on macos/QMK Toolbox/AppDelegate.m
> +
```suggestion
```

2022-04-30 05:13 UTC, fauxpark requested changes

2022-04-30 05:13 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
> +		9B7999EE280AA1D0007469DA /* WB32DFUDevice.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = WB32DFUDevice.m; sourceTree = "<group>"; };
```suggestion
		9B7999ED280AA1C8007469DA /* WB32DFUDevice.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = WB32DFUDevice.h; sourceTree = "<group>"; };
		9B7999EE280AA1D0007469DA /* WB32DFUDevice.m */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.objc; path = WB32DFUDevice.m; sourceTree = "<group>"; };
```

2022-04-30 05:30 UTC, wb-Joy commented
> Waiting for [Homebrew/homebrew-core#98739](https://github.com/Homebrew/homebrew-core/pull/98739)

Has been merged.

2022-04-30 05:46 UTC, zvecr commented
You still need to pull down the "official" binary from homebrew and update the PR.

2022-04-30 05:47 UTC, wb-Joy commented
> You still need to pull down the "official" binary from homebrew and update the PR.

I've already done that.

2022-04-30 09:02 UTC, zvecr commented
Ignore me, for whatever reason the sha256 didnt match. Just retried by steps and they do indeed match.

2022-04-30 09:37 UTC, wb-Joy commented
> ~Ignore me, for whatever reason the sha256 didnt match. Just retried by steps and they do indeed match.~
> 
> You have uploaded the `monterey` bottle artifact, rather than the `catalina` ones.
> 
> executable should be `5becb921ab4cb3b1cce87418720fb3e8b5cc650eea0f0934815b2d291af2950a` but is `eca41b6ce4e88ff2c25eb8932adde0823a8e98c43426a3e8a859e3aa073da7b1`.

It's been re-uploaded.

2022-04-30 13:02 UTC, fauxpark commented
Still wrong - the Homebrew placeholder needs to be changed.
This PR:
```
fauxpark@marissa:downloads$ otool -L wb32-dfu-updater_cli  
wb32-dfu-updater_cli:
	@@HOMEBREW_PREFIX@@/opt/libusb/lib/libusb-1.0.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
fauxpark@marissa:downloads$ shasum -a256 wb32-dfu-updater_cli
5becb921ab4cb3b1cce87418720fb3e8b5cc650eea0f0934815b2d291af2950a  wb32-dfu-updater_cli
```

What it should be:
```
fauxpark@marissa:bin$ otool -L wb32-dfu-updater_cli  
wb32-dfu-updater_cli:
	@executable_path/../Frameworks/libusb-1.0.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
fauxpark@marissa:bin$ shasum -a256 wb32-dfu-updater_cli
7bfd47724864c8042fb169aa6b6dd5ceef03ca477d29f9badd345d2503d7064a  wb32-dfu-updater_cli
```

See #342

2022-04-30 15:03 UTC, wb-Joy commented
Okay, the placeholder have been changed. That should be all right.

2022-05-15 09:08 UTC, fauxpark requested changes
One last thing.

2022-05-15 09:08 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
>  		3AFD4BD1281AB86800ADCB65 /* libhidapi.0.dylib in CopyFiles */ = {isa = PBXBuildFile; fileRef = 3AFD4BCF281AB83C00ADCB65 /* libhidapi.0.dylib */; settings = {ATTRIBUTES = (CodeSignOnCopy, ); }; };
```suggestion
		3AFD4BD1281AB86800ADCB65 /* libhidapi.0.dylib in CopyFiles */ = {isa = PBXBuildFile; fileRef = 3AFD4BCF281AB83C00ADCB65 /* libhidapi.0.dylib */; settings = {ATTRIBUTES = (CodeSignOnCopy, ); }; };
		9B7999EF280AA1D0007469DA /* WB32DFUDevice.m in Sources */ = {isa = PBXBuildFile; fileRef = 9B7999EE280AA1D0007469DA /* WB32DFUDevice.m */; };
		9BE10718275F4CFE00C708D5 /* wb32-dfu-updater_cli in Resources */ = {isa = PBXBuildFile; fileRef = 9BE10717275F4CFE00C708D5 /* wb32-dfu-updater_cli */; };
```

2022-05-15 09:08 UTC, fauxpark commented on macos/QMK Toolbox.xcodeproj/project.pbxproj
>  		3AFD4BCF281AB83C00ADCB65 /* libhidapi.0.dylib */ = {isa = PBXFileReference; lastKnownFileType = "compiled.mach-o.dylib"; path = libhidapi.0.dylib; sourceTree = "<group>"; };
```suggestion
		3AFD4BCF281AB83C00ADCB65 /* libhidapi.0.dylib */ = {isa = PBXFileReference; lastKnownFileType = "compiled.mach-o.dylib"; path = libhidapi.0.dylib; sourceTree = "<group>"; };
		9B7999ED280AA1C8007469DA /* WB32DFUDevice.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = WB32DFUDevice.h; sourceTree = "<group>"; };
		9B7999EE280AA1D0007469DA /* WB32DFUDevice.m */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.objc; path = WB32DFUDevice.m; sourceTree = "<group>"; };
		9BE10717275F4CFE00C708D5 /* wb32-dfu-updater_cli */ = {isa = PBXFileReference; lastKnownFileType = "compiled.mach-o.executable"; path = "wb32-dfu-updater_cli"; sourceTree = "<group>"; };
```

2022-05-15 09:29 UTC, fauxpark approved these changes

2022-05-20 14:03 UTC, merged